language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - libsfml-dev

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  - cd src/ML/pytorch
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-latest.zip --quiet
  - unzip libtorch-shared-with-deps-latest.zip
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/src/ML/pytorch/libtorch/lib
  - cd ../../..

script:
  - make all
  - make docu

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/doxygen/html
  github-token: $GITHUB_API_KEY
  on:
    branch: master
