
#ifndef colorlist_H_
#define colorlist_H_

#include <SFML/Graphics.hpp>
#include <vector>

/** \brief This Class stores a List of well-distinguishable Colors. (Color Values)
 *
 * the Class stores 1 variable: list, which is a vector with different Color Values.
 * you can initialize a "colorlist" with an integer k. (See constructors)
 * Also there are update methods, to initialize variables after the constructor call.
 */
class colorlist {
    private:
        std::vector<sf::Color> list; ///< vector of well-distinguishable Colors
    public:
        /** 
         * the complete constructor, which initialize the private vector
         * of Color values list.
         *
         * \param numbOfKmers an integer which set the size of list
         */
        colorlist(int numbOfKmers);
        
        /**
         * The standard constructor, which initialize a empty vector
         * of Color values
         */
        colorlist();

        /**
         * this Method will create a vector of different Color values. 
         * the first 13 colors are hard coded with some values out of the web and
         * the next possible colors are generated by an algorithm.
         *
         * \param numbOfKmer an integer which set the size of list
         */
        void updateList(int numbOfKmers);

        /**
         * Method to return the private vector of Color values list
         *
         * \return a vector of different Color values
         */
        std::vector<sf::Color> giveList();
};

#endif //colorlist_H_
