all:
	cd ColorPalette; make all
	cd GUI; make all
	cd VisualizationTest; make all
	cd StaticGraph; make all

clean:
	cd GUI; make clean
	cd ColorPalette; make clean
	cd VisualizationTest; make clean
	cd StaticGraph; make clean
